# These are supported funding model platforms

github: [crc137]  # GitHub Sponsors username

custom: ["https://sponsors.coonlink.com/crc137", "https://tonhub.com/transfer/UQCdxFNpC5j-bkMNVd_HB0QQY6AADviQN2mpChp8-hNgI9KT"]
