# These are supported funding model platforms

github: [crc137] 
patreon: 
open_collective: 
ko_fi: 
tidelift:
community_bridge: 
liberapay: 
issuehunt: 
lfx_crowdfunding: 
polar: 
buy_me_a_coffee:
thanks_dev: 
custom:
  - 'https://tonhub.com/transfer/UQCdxFNpC5j-bkMNVd_HB0QQY6AADviQN2mpChp8-hNgI9KT'  # TON
  - 'https://tonhub.com/transfer/UQCOx0Msk2uoTlv6xljK0EL89dAfSB4zODoAqle7j9LkcmhX'  # USDT (TON)
  - 'bitcoin:1NMxRH5Mi4bj6r7mkfCk9r72yVVhxUqXBg'  # BTC
  - 'ethereum:0x4d722270e2aBB5E43d98846179fd694769AA9aE4'  # ETH
